---
version: 1.2.0
slug: porcupine1-withcn
name: porcupine1withcn
description: porcupine1 using the Wyoming protocol with cn support
url: https://github.com/Tomywang999/hassio-addons/tree/master/porcupine1
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
options:
  sensitivity: 0.5
  debug_logging: false
schema:
  sensitivity: float
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
